[package]
name = "opds"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
atom_syndication = "0.10"
attohttpc = "0.17"
clap = "3.0.0-beta.2"
termion = "1.5"
thiserror = "1.0"
tui = "0.15"
