[package]
name = "opds"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"

[dependencies]
atom_syndication = "0.11"
attohttpc = "0.18"
lazy_static = "1.4"
termion = "1.5"
thiserror = "1.0"
tui = "0.17"
url = "2.2"

[dependencies.clap]
version = "3.0"
features = ["derive"]

[dependencies.log]
version = "0.4"
features = ["std"]
