[package]
name = "opds"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"

[dependencies]
atom_syndication = "0.11"
attohttpc = "0.18"
clap = "3.0.0-beta.2"
lazy_static = "1.4"
termion = "1.5"
thiserror = "1.0"
tui = "0.16"
url = "2.2"

[dependencies.log]
version = "0.4"
features = ["std"]
